### ISSUE TITLE
能提供下对应的版本吗？

### ISSUE THREAD

**Issue by deathrush** [FineReport-hack/hackFR8#1]
感谢大神，但是貌似版本不对的话会报错。能否分享下对应的版本原文件，谢谢。

**Comment by dennis-xlc** [comment]
我做了一些改动，请尝试按照最新的步骤。谢谢。

**Comment by deathrush** [comment]
谢谢大神。
bat脚本有个问题：第18行WEB-INF\resources最后的那个s缺少
![image](https://cloud.githubusercontent.com/assets/10840992/15809793/0d244aba-2bca-11e6-8f62-9acd6e885bd1.png)
另外建议在开头增加CD /d %~dp0确保进入脚本所在目录

**Comment by dennis-xlc** [comment]
Thanks for pointing this bug out~

Then I will close this issue.
